spring.application.name=tdd1bim
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/todo}
spring.datasource.username=${DB_USER:todo}
spring.datasource.password=${DB_PASSWORD:todo}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.sql.init.mode=always
server.port=${PORT:8080}
